Simulate build failure notification

diff --git a/.github/workflows/msteams-notification-demo.yml b/.github/workflows/msteams-notification-demo.yml
--- a/.github/workflows/msteams-notification-demo.yml
+++ b/.github/workflows/msteams-notification-demo.yml
@@ -18,7 +18,8 @@ jobs:
     steps:
       - name: Build job 2
         run: |
-          echo "Simulating a build job 2"
+          echo "Simulating a failure of build job 2"
+          exit 1
           
   build-3:
     runs-on: ubuntu-latest
